CREATE TABLE `assessmentScales` (
	`id` int AUTO_INCREMENT NOT NULL,
	`residentId` int NOT NULL,
	`scaleType` enum('barthel','norton') NOT NULL,
	`totalScore` int NOT NULL,
	`assessmentDate` timestamp NOT NULL,
	`assessmentData` text NOT NULL,
	`interpretation` text,
	`notes` text,
	`assessedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `assessmentScales_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`residentId` int NOT NULL,
	`medicationName` varchar(200) NOT NULL,
	`activeIngredient` varchar(200),
	`dosage` varchar(100) NOT NULL,
	`unit` varchar(50) NOT NULL,
	`administrationRoute` enum('oral','sublingual','intravenous','intramuscular','subcutaneous','topical','rectal','inhalation','ophthalmic','otic','nasal') NOT NULL,
	`frequency` varchar(100) NOT NULL,
	`scheduleType` enum('acute','chronic') NOT NULL,
	`startDate` date NOT NULL,
	`endDate` date,
	`monday` boolean DEFAULT false,
	`tuesday` boolean DEFAULT false,
	`wednesday` boolean DEFAULT false,
	`thursday` boolean DEFAULT false,
	`friday` boolean DEFAULT false,
	`saturday` boolean DEFAULT false,
	`sunday` boolean DEFAULT false,
	`administrationTimes` text NOT NULL,
	`indication` text,
	`prescribedBy` varchar(200),
	`notes` text,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int NOT NULL,
	CONSTRAINT `medications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nursingNotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`residentId` int NOT NULL,
	`category` enum('general','vital_signs','medication','nutrition','hygiene','mobility','behavior','wound_care','incident') NOT NULL,
	`title` varchar(200) NOT NULL,
	`content` text NOT NULL,
	`priority` enum('low','normal','high','urgent') DEFAULT 'normal',
	`noteDate` timestamp NOT NULL,
	`recordedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nursingNotes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `residents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`nif` varchar(20),
	`nss` varchar(20),
	`nsip` varchar(20),
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`birthDate` date,
	`gender` enum('male','female','other'),
	`admissionDate` date NOT NULL,
	`lastAdmissionDate` date,
	`birthPlace` varchar(200),
	`roomId` int,
	`bedNumber` int,
	`status` enum('active','discharged','deceased') NOT NULL DEFAULT 'active',
	`contactPhone` varchar(20),
	`contactEmail` varchar(320),
	`emergencyContactName` varchar(200),
	`emergencyContactPhone` varchar(20),
	`emergencyContactRelation` varchar(100),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int NOT NULL,
	CONSTRAINT `residents_id` PRIMARY KEY(`id`),
	CONSTRAINT `residents_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `rooms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`name` varchar(100) NOT NULL,
	`roomType` enum('single','double','triple','shared') NOT NULL,
	`floor` int,
	`wing` varchar(50),
	`totalBeds` int NOT NULL,
	`availableBeds` int NOT NULL,
	`hasPrivateBathroom` boolean DEFAULT false,
	`hasBalcony` boolean DEFAULT false,
	`isAccessible` boolean DEFAULT false,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rooms_id` PRIMARY KEY(`id`),
	CONSTRAINT `rooms_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `vitalSigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`residentId` int NOT NULL,
	`measurementType` enum('blood_pressure','heart_rate','respiratory_rate','oxygen_saturation','temperature','glucose','weight') NOT NULL,
	`systolicBP` int,
	`diastolicBP` int,
	`heartRate` int,
	`respiratoryRate` int,
	`oxygenSaturation` decimal(5,2),
	`temperature` decimal(4,2),
	`glucose` int,
	`weight` decimal(5,2),
	`notes` text,
	`measurementDate` timestamp NOT NULL,
	`recordedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `vitalSigns_id` PRIMARY KEY(`id`)
);
